# Generated by Django 2.1.3 on 2018-12-06 10:42

from django.db import migrations, models
import system.models.system_settings


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_systemsettings_contract_vot_manager_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemsettings',
            name='contract_vot_manager_address',
            field=models.CharField(blank=True, max_length=42, null=True, validators=[system.models.system_settings.validate_address]),
        ),
    ]
