# Generated by Django 2.1.3 on 2018-11-15 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EIP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file_name', models.CharField(max_length=255)),
                ('file_download_url', models.URLField()),
                ('file_content', models.TextField()),
                ('file_sha', models.CharField(max_length=100)),
                ('eip_num', models.CharField(max_length=10)),
                ('eip_title', models.CharField(max_length=225)),
                ('eip_status', models.CharField(choices=[('DRAFT', 'draft'), ('ACTIVE', 'active'), ('LAST_CALL', 'last call'), ('REPLACED', 'replaced'), ('ACCEPTED', 'accepted'), ('FINAL', 'final'), ('DEFERRED', 'deferred'), ('OTHER', 'other')], max_length=30)),
                ('eip_type', models.CharField(choices=[('STANDARDS_TRACK', 'standards track'), ('INFORMATIONAL', 'informational'), ('META', 'meta'), ('OTHER', 'other')], max_length=30)),
                ('eip_category', models.CharField(blank=True, choices=[('CORE', 'core'), ('NETWORKING', 'networking'), ('INTERFACE', 'Interface'), ('ERC', 'erc'), ('OTHER', 'other')], max_length=30, null=True)),
                ('eip_authors', models.CharField(max_length=255)),
                ('eip_created', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
