# Generated by Django 2.1.3 on 2018-12-14 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eip', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eip',
            name='eip_created_raw',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='eip',
            name='eip_created',
            field=models.DateField(blank=True, null=True),
        ),
    ]
