# Generated by Django 2.1.7 on 2019-02-25 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eip', '0004_auto_20190224_0850'),
    ]

    operations = [
        migrations.AddField(
            model_name='eip',
            name='is_voting_active',
            field=models.BooleanField(default=False),
        ),
    ]
