# Generated by Django 2.1.3 on 2018-12-26 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EthVoter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('address', models.CharField(max_length=42)),
                ('last_block', models.BigIntegerField(default=0)),
                ('last_tx_hash', models.CharField(blank=True, max_length=66, null=True)),
                ('used_gas', models.BigIntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
