# Generated by Django 2.1.3 on 2019-01-02 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ethereum_client', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoteLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('voter', models.CharField(max_length=42)),
                ('selected_option', models.IntegerField(choices=[(1, 'yay'), (2, 'nay'), (3, 'abstain')])),
                ('proposal_id', models.IntegerField()),
                ('block_number', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VotingDetailsLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('proposal_id', models.IntegerField()),
                ('is_voting_open', models.BooleanField()),
                ('block_number', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
