# Generated by Django 2.1.7 on 2019-02-24 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ethereum_client', '0002_votelog_votingdetailslog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ethvoter',
            name='address',
            field=models.CharField(max_length=42, unique=True),
        ),
    ]
