# Generated by Django 2.1.3 on 2018-11-16 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.CharField(max_length=255)),
                ('post_url', models.URLField(unique=True)),
                ('choice', models.CharField(choices=[('YAY', 'yay'), ('NAY', 'nay'), ('ABSTAIN', 'abstain')], max_length=7)),
                ('status', models.CharField(choices=[('PENDING', 'pending'), ('REJECTED', 'rejected'), ('APPROVED', 'approved')], default='PENDING', max_length=8)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
