# Generated by Django 2.1.3 on 2018-11-19 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('eip', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.CharField(max_length=255)),
                ('proof_url', models.URLField()),
                ('choice', models.CharField(choices=[('YAY', 'yay'), ('NAY', 'nay'), ('ABSTAIN', 'abstain')], max_length=7)),
                ('status', models.CharField(choices=[('PENDING', 'pending'), ('REJECTED', 'rejected'), ('APPROVED', 'approved')], default='PENDING', max_length=8)),
                ('eip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eip.EIP')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
