# Generated by Django 2.1.3 on 2018-11-23 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('influencer', '0001_initial'),
        ('stance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stance',
            name='influencer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='influencer.Influencer'),
        ),
    ]
