# Generated by Django 2.1.3 on 2018-12-18 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stance', '0002_stance_influencer'),
    ]

    operations = [
        migrations.AddField(
            model_name='stance',
            name='proof_last_check',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='stance',
            name='proof_type',
            field=models.CharField(choices=[('TWITTER', 'twitter'), ('OTHER', 'other')], default='OTHER', max_length=20),
        ),
    ]
