# Generated by Django 2.1.7 on 2019-04-06 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stance', '0004_auto_20181220_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='stance',
            name='author_from_social',
            field=models.CharField(choices=[('TWITTER', 'twitter'), ('PEEPETH', 'peepeth')], default='TWITTER', max_length=50),
        ),
    ]
