# Generated by Django 2.1.3 on 2018-11-22 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Influencer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('twitter_id', models.CharField(max_length=20, unique=True)),
                ('score', models.DecimalField(decimal_places=18, max_digits=30)),
                ('name', models.CharField(max_length=255)),
                ('screen_name', models.CharField(max_length=100)),
                ('friends_count', models.IntegerField()),
                ('followers_count', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
