# Generated by Django 2.1.7 on 2019-05-02 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('influencer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='influencer',
            old_name='friends_count',
            new_name='following_count',
        ),
    ]
