# Generated by Django 2.1.7 on 2019-05-02 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('influencer', '0002_auto_20190502_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='influencer',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
